### ISSUE TITLE
UTF-8 BOM in Russian dictionary

### ISSUE THREAD

**Issue by alexshpilkin** [josephwright/translator#1]
A [UTF-8 BOM](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8) (EF, BB, BF; U+FEFF) appears to have snuck into the first bytes of `translator-basic-dictionary-Russian.dict` (and possibly other files), leading to my TeX installation choking on it. A `\DeclareUnicodeCharacter{FEFF}{}` right before `\begin{document}` fixes the issue, but it would be better to take the BOM out. (Note that the BOM is invisible in some, but not all, text editors.)

**Comment by josephwright** [comment]
Odd ... I'll take a look

**Comment by josephwright** [comment]
Looks like they've been present since day one

**Comment by alexshpilkin** [comment]
Yes, it does; sorry that I forgot to mention this. Seems like the dictionary shouldn’t have worked in the first place. I’ve only noticed it now that I’ve both updated my rolling-release TeX distribution and had to recompile a dormant book project. Also, the latest beamer release from Nov 11 is the only one to include the Russian dictionary at all, so I suppose it just hasn’t gotten to a lot of people yet.

**Comment by alexshpilkin** [comment]
Oh. I’ve just realized what you might have been surprised about. Let me be clear: my document never actually _used_ translator or beamer, but a (possibly updated) dependency must have pulled translator in anyway (I’ll do the log-paren-matching exercise later if it’s necessary to know which one), and translator in turn used babel’s language setting. Thus the document compiled when there was no Russian dictionary, but promptly refused to when a broken one got installed.
