### ISSUE TITLE
Issue with turkish translation 

### ISSUE THREAD

**Issue by seloumi** [josephwright/translator#17]
Beamer example with turkish produce error 
`Too many }'s. \providetranslation{Four}{D\"[o}rt}
`
The issue  is discribed here https://tex.stackexchange.com/questions/542179/fixing-beamer-turkish-translation 

```latex
\documentclass[turkish]{beamer}

\begin{document}
\begin{frame}
\today
\end{frame}

\end{document}
```

https://github.com/josephwright/translator/blob/3d26326c12385325a9ea439d683dc57b12e7729e/translator-numbers-dictionary-Turkish.dict#L19

**Comment by josephwright** [comment]
Fixed by https://github.com/josephwright/translator/pull/16
